services:
  - type: web
    name: endsem-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CLIENT_URL
        sync: false

  - type: static_site
    name: endsem-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: endsem-backend
          envVarKey: RENDER_EXTERNAL_URL
